# Proceso de desarrollo para proceso de CSV

Dado el desarrollo de mi proyecto y debido a que mi ase tiene vaores Nan, y el registro historioco se basa desde 2005, usare un desarrollo clasico para limpiar los datis y lograr extraes el promedio de afluencia por linea de año reciente

In [4]:
import pandas as pd 
import numpy as np

csv = "./data/afluenciamb_simple_05_2026.csv"

df = pd.read_csv(csv)

df['afluencia'] = pd.to_numeric(df['afluencia'], errors='coerce')
df = df.dropna(subset=['afluencia'])

anio_reciente = df['anio'].max()
df_filtrado = df[df['anio'] == anio_reciente]

lineas_objetivo = ['Línea 1', 'Línea 2','Línea 3','Línea 4']
afluencias_promedio = {}

for line in lineas_objetivo :
    promedio = df_filtrado[df_filtrado['linea'] == line]['afluencia'].mean()
    afluencias_promedio[line] = promedio if not np.isnan(promedio) else 1.0


base_costos_geograficos = np.array([
    [10, 25, 15, 30],
    [20, 12, 10, 15],
    [30, 15, 25, 10],
    [15, 20, 20, 25]
])

max_afluencia = max(afluencias_promedio.values())
factores_demanda = np.array([afluencias_promedio[l] / max_afluencia for l in lineas_objetivo])

S = base_costos_geograficos / factores_demanda
S = np.round(S, 2)

print("Matriz S de COstos Operacionales 4x4 generada:")
print(S)

Matriz S de COstos Operacionales 4x4 generada:
[[ 10.    56.56  37.55 150.68]
 [ 20.    27.15  25.03  75.34]
 [ 30.    33.94  62.58  50.23]
 [ 15.    45.25  50.07 125.57]]
